# NUMPY 
This Notebook will cover the following topics:    
- Numpy basics
- Built-in methods and functions 
- Obtain shape, length and type of Numpy arrays
- Reshape 
- Minimum and maximum and their indices
- Mathematical Operations
- Indexing and slicing 
- Selection 

In [11]:
import numpy as np

In [12]:
# One-dimensional array 
my_list = [5, 3, 10]
my_list

[5, 3, 10]

In [13]:
y = np.array(my_list)

In [14]:
print(y)
type(y)

[ 5  3 10]


numpy.ndarray

##### Multi-dimensional Matrix ( 2D Array ) 

In [15]:
matrix_MD = np.array([[1,4,6],[3,8,4]])

print(matrix_MD)

type(matrix_MD)

[[1 4 6]
 [3 8 4]]


numpy.ndarray

- Generate 2D matrix**

In [16]:
matrix_2D = np.empty([3, 3], np.uint8)
print(matrix_2D)

[[1 0 0]
 [1 1 0]
 [1 1 1]]


In [17]:
x = np.full((3, 3, 3), dtype=np.int16, fill_value = 3)
print(x)

[[[3 3 3]
  [3 3 3]
  [3 3 3]]

 [[3 3 3]
  [3 3 3]
  [3 3 3]]

 [[3 3 3]
  [3 3 3]
  [3 3 3]]]


##### Multi-dimensional Matrix ( 3D Array ) 

In [18]:
matrix_3D = np.array([[[1, 2, 3], [4, 5, 6]],[[0, -1, -2], [-3, -4, -5]]], np.int16)
print(matrix_3D)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 0 -1 -2]
  [-3 -4 -5]]]


In [19]:
print(matrix_3D [1, 1, 2])

-5


In [20]:
print(matrix_3D [:, 1, 1])

[ 5 -4]


##### **NumPy Constants**

In [21]:
print(np.inf)
print(np.NAN)
print(np.NINF)
print(np.NZERO)
print(np.PZERO)

print(np.e)
print(np.euler_gamma)
print(np.pi)

inf
nan
-inf
-0.0
0.0
2.718281828459045
0.5772156649015329
3.141592653589793


#### BUILT-IN METHODS AND FUNCTIONS

###### **"rand()" uniform** distribution between 0 and 1

In [22]:
x = np.random.rand(10)
print(x)

[0.30414328 0.53639017 0.69679057 0.66202588 0.07350678 0.1607949
 0.66269741 0.92910127 0.60264121 0.87175376]


In [23]:
x = np.random.rand(5, 5)
print(x)

[[0.47355564 0.45867107 0.79526717 0.48082195 0.83013161]
 [0.54758064 0.96618252 0.33456512 0.54782879 0.83798255]
 [0.62976678 0.65035567 0.07283851 0.28820895 0.16594416]
 [0.10218323 0.35128385 0.45606937 0.92578473 0.32613507]
 [0.53926677 0.35010106 0.08570825 0.71327567 0.84761158]]


###### **"randn()" normal** distribution ****between 0 and 1****

In [24]:
x = np.random.randn(10)
print(x)

[ 1.97963037 -0.23587473  2.34354855 -0.05253681  0.92316944 -0.75805843
 -1.42322959  0.66113621 -0.97165674  2.54261451]


###### **"randint"** is used to generate **random integers between upper and lower bounds**

In [25]:
x = np.random.randint(1,10)
print(x)

5


###### **"randint"** is used to generate random integers between upper and lower bounds

In [26]:
x = np.random.randint( low = 0, high = 9, size = 10)
print(x)

[0 4 2 3 5 5 2 1 1 3]


In [27]:
x = np.random.randint(1,80,15)
print(x)
len(x)

[63 52  8 19  8 20 23 17 60 12  1  4  5 14 71]


15

In [28]:
x = np.arange(1, 50)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]


In [29]:
x = np.arange(1,50,3)
print(x)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]


###### Generate **UNIT Matrix** use eye()

In [30]:
x = np.eye(5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
# Array of ones
x = np.ones(15)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [32]:
# Matrices of ones
x = np.ones((5, 5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
np.ones( (2,3,4), dtype=np.int16 )                # dtype can also be specified

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

##### **Uninitialized**

In [34]:
np.empty( (2,3) )                                 # uninitialized

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
# zerooooooooooooooooo
x = np.zeros(5)
x

array([0., 0., 0., 0., 0.])

In [36]:
np.linspace( 0, 2, 9 )

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

##### **Matrix creation routines**

In [37]:
x = np.tri(3, 3, k=0, dtype=np.uint16)                            
print(x)

[[1 0 0]
 [1 1 0]
 [1 1 1]]


In [38]:
x = np.tri(5, 5, k=1, dtype=np.uint16)
print(x)

[[1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [39]:
x = np.ones((5, 5), dtype=np.uint8)             # lower tringular Matrix 
y = np.tril(x, k=-1)
print(y)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]]


In [40]:
x = np.ones((5, 5), dtype=np.uint8)             # upper tringular Matrix 
y = np.triu(x, k=1)
print(y)

[[0 1 1 1 1]
 [0 0 1 1 1]
 [0 0 0 1 1]
 [0 0 0 0 1]
 [0 0 0 0 0]]


#### SHAPE, LENGTH AND TYPE OF NUMPY ARRAYS

###### **get shape**

In [41]:
y.shape

(5, 5)

In [42]:
matrix_MD.shape

(2, 3)

In [43]:
matrix_MD.dtype                  # ( output int32  means 32 bit integer)

dtype('int32')

In [44]:
print(matrix_MD.shape)
print(matrix_MD.ndim)
print(matrix_MD.dtype)

print(matrix_MD.size)
print(matrix_MD.nbytes)

(2, 3)
2
int32
6
24


##### **RESHAPE**
- can reshape One dimesional matrix

In [45]:
x = np.random.randn(10)
x.reshape(2,5)

array([[ 0.60160417, -2.01548171, -0.54253388, -1.62407187, -0.25820784],
       [ 1.06956813, -1.60567139,  0.40541319, -1.30697744, -0.75976221]])

In [46]:
x = np.matrix(np.arange(12).reshape((3,4)));
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


#### **MAX AND MIN VALUES AND THEIR INDEX**

###### **To get the maximum / largest value in a Numpy array and its indices using numpy.amax().**

numpy.amax(a, axis=None, out=None, keepdims=<no value>, initial=<no value>)

###### Arguments :

 - **a** : numpy array from which it needs to find the maximum value.
 - **axis** : It’s optional and if not provided then it will flattened the passed numpy array and returns the max value in it.
 
        1 If it’s provided then it will return for array of max values along the axis
        2 If axis=0 then it returns an array containing max value for each columns.
        3 If axis=1 then it returns an array containing max value for each row

###### This is the same as **ndarray.max**, but returns a matrix object where **ndarray.max** would return an **ndarray**.

In [47]:
x = np.matrix(np.arange(12));
print(x)

[[ 0  1  2  3  4  5  6  7  8  9 10 11]]


In [48]:
 x.max()

11

In [49]:
x.max(1)

matrix([[11]])

In [50]:
x.max(0)

matrix([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [51]:
# Obtain the index of the max value
x.argmax()

11

In [52]:
# Obtain the index of the min value
y.argmin()

0

###### **Find index of max value of matrix X :**

In [53]:
result = np.where(x == np.amax(x))
 
print('Returned tuple of arrays :', result)
print('List of Indices of maximum element :', result[0])

Returned tuple of arrays : (array([0], dtype=int64), array([11], dtype=int64))
List of Indices of maximum element : [0]


##### **Find maximum value & its index in a 2D Numpy Array**

In [54]:
matrix_MD1 = np.array([[1,4,6],[3,8,4],[12,7,5]])

print(matrix_MD1)

[[ 1  4  6]
 [ 3  8  4]
 [12  7  5]]


- To find maximum value from complete 2D numpy array we will not pass axis in numpy.amax()

In [55]:
maxValue = np.amax(matrix_MD1)
print(maxValue)

12


- To find maximum value from complete 2D numpy array we will not pass axis in numpy.amin()

In [56]:
minValue = np.amin(matrix_MD1)
print(minValue)

1


##### **Find max values along the axis in 2D numpy array | max in rows or columns:**
 - If we pass **axis=0** in **numpy.amax()** then it returns an array containing max value for each **column**
 - **numpy.amax()** then it returns an array containing max value for each **column**

In [57]:
maxInColumns = np.amax(matrix_MD1, axis=0)
 
print('Max value of every column: ', maxInColumns)

Max value of every column:  [12  8  6]


- If we pass **axis = 1** in **numpy.amax()** then it returns an array containing max value for each **row**
- **numpy.amax()** then it returns an array containing max value for each **row**

In [58]:
maxInrow = np.amax(matrix_MD1, axis=1)
 
print('Max value of every row: ', maxInrow)

Max value of every row:  [ 6  8 12]


##### **Find index of maximum value from 2D numpy array:**
- Contents of the 2D numpy array a **matrix_MD1** are 

In [59]:
result = np.where(matrix_MD1 == np.amax(matrix_MD1))
 
print('Tuple of arrays returned : \n', result)

 
print('\n List of coordinates of maximum value in Numpy array : ')

# zip the 2 arrays to get the exact coordinates
listOfCordinates = list(zip(result[0], result[1]))

# travese over the list of cordinates
for cord in listOfCordinates:
    print(cord)

Tuple of arrays returned : 
 (array([2], dtype=int64), array([0], dtype=int64))

 List of coordinates of maximum value in Numpy array : 
(2, 0)


#### **MATHEMATICAL OPERATIONS**

In [60]:
x = np.arange(1, 5)
y = np.arange(1, 5)

print(x+y)

[2 4 6 8]


In [61]:
z = x**2
print(z)

[ 1  4  9 16]


In [62]:
k = np.sqrt(z)
k

array([1., 2., 3., 4.])

In [63]:
z = np.exp(y)
z

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

#### **ELEMENTS SLICING AND INDEXING**

In [64]:
x = np.random.randint(1,10, 10)
x

array([7, 6, 1, 3, 3, 9, 3, 1, 1, 9])

In [65]:
x[3]

3

In [66]:
x[0:3]

array([7, 6, 1])

In [67]:
# Broadcasting, altering several values in a numpy array at once
x[0:6] = 10
x

array([10, 10, 10, 10, 10, 10,  3,  1,  1,  9])

In [68]:
matrix = np.random.randint(1,10, (5, 5))
print(matrix)

[[8 8 7 4 2]
 [9 7 1 8 6]
 [6 8 6 8 4]
 [6 3 4 3 6]
 [4 3 9 4 7]]


In [69]:
# Get a row from a mtrix
matrix[3]

array([6, 3, 4, 3, 6])

In [70]:
# Get element
matrix[0][2]

7

In [71]:
mini_matrix = matrix[:3]
mini_matrix

array([[8, 8, 7, 4, 2],
       [9, 7, 1, 8, 6],
       [6, 8, 6, 8, 4]])

In [72]:
mini_matrix = matrix[2:]
mini_matrix

array([[6, 8, 6, 8, 4],
       [6, 3, 4, 3, 6],
       [4, 3, 9, 4, 7]])

In [73]:
mini_matrix = matrix[:, :2]
mini_matrix

array([[8, 8],
       [9, 7],
       [6, 8],
       [6, 3],
       [4, 3]])

In [74]:
mini_matrix = matrix[:, 2:]
mini_matrix

array([[7, 4, 2],
       [1, 8, 6],
       [6, 8, 4],
       [4, 3, 6],
       [9, 4, 7]])

##### **ELEMENTS SELECTION**

In [75]:
new_matrix = matrix[matrix>3]
new_matrix

array([8, 8, 7, 4, 9, 7, 8, 6, 6, 8, 6, 8, 4, 6, 4, 6, 4, 9, 4, 7])

In [76]:
new_matrix = matrix[matrix%2==0]
new_matrix

array([8, 8, 4, 2, 8, 6, 6, 8, 6, 8, 4, 6, 4, 6, 4, 4])